language: objective-c
osx_image: xcode7.3

branches:
  only:
  - qt-bottle

script:
- brew install --only-dependencies --build-bottle albertosottile/qt59/qt
- travis_wait 90 brew install --build-bottle albertosottile/qt59/qt
- brew bottle albertosottile/qt59/qt

install:
- brew update
- curl -O http://syncplay.s3.amazonaws.com/qt595.rb
- mkdir qt59
- mv qt595.rb qt59/qt.rb
- cd qt59
- git init
- git add qt.rb
- git commit -m "Initial commit"
- cd ..
- brew tap albertosottile/homebrew-qt59 qt59

before_deploy:
- ls -al qt-*

deploy:
  skip_cleanup: true
  on: qt59
  provider: bintray
  file: "bintray.json"
  user: alby128
  key:
    secure: "IHR96zDrlsxIVJF3SHZoQ5N8omEbneZgh1NN+qAkZshkadvXdt16rBXPzsifmTgiw9EeOjLpzCZvdnjDraYO+Pj/P5MSE3Zu2rVJ6FDFD9VjWcYKXqWFkRa21sm2oo0Xe+1SKnFqY8ACXKA1vFY448lBd0QnJhtbTJXHQLSJeoYm+8fDaQD8iPCanNac60nUsxGoRNVmSG/xl7DrENIdJ+enkvVleqh4ur6h+Urds8gXGncdj+aYQqmtVpbiKDS9tBBRKdnspi5JRBckd609FqB+AQA+l7vjnCBA3+XeHNLW/XE2l4g8D3msIrDpGNymLjHviL5wpm/p2MfaeoOxeJgeVl+tr/vA3gZm/TpYuo18jqFToUfPGm5Ox/SP4uT2drk7j8muHHwoFRflgIvqC96ormS3xCBBikUb87X9v7hTK722YWo7L1uH6ZVrTNhg4k4XS6x1+tg418lKkV034nIcDoXo/WUazRbwfPGhOtfdOVGXzbtAw1sR9ug0PwXWp1cxWI3Nlswo6kz3r9Qy2AHR2Wd75BAly7AFxRiubEWo+y0uDKC/JEHi7K2oaBsB7+5IvUw9zaisImrhjNDD2/ZDGrdCLZfzwHrv5DfX62fej8CHXdblcQ1BfIRUDYr6fNfLMvtJYiOs6KFgYn5fBjI563siVa/BRKPCfnFELTg="