language: objective-c
osx_image: xcode9.3

branches:
  only:
  - qt59-highsierra

env:
  global:
    - PYSIDE_BRANCH=5.9
    - QT_VER_SHORT=5.9
    - QT_VER=5.9.4
    - CI_QMAKE=${HOME}/Qt-${QT_VER}/${QT_VER}/clang_64/bin/qmake
    - LIBCLANG_FILE=libclang-release_50-mac-clazy.7z
    - QT_INSTALLER_FILE=qt-opensource-mac-x64-${QT_VER}
    - QT_INSTALL_PATH=${HOME}/Qt-${QT_VER}

script:
- python2 setup.py bdist_wheel --debug --ignore-git --standalone --no-examples --macos-use-libc++ --qmake=${CI_QMAKE} --cmake=/usr/local/bin/cmake --jobs=3

before_install:
- which python2
- which pip2
- brew install libxslt libxml2
- pip2 install --upgrade setuptools wheel
- brew install tree p7zip
- curl -L -O https://download.qt.io/archive/qt/${QT_VER_SHORT}/${QT_VER}/${QT_INSTALLER_FILE}.dmg
- hdiutil attach -noverify ${QT_INSTALLER_FILE}.dmg
- travis_wait 20 /Volumes/${QT_INSTALLER_FILE}/${QT_INSTALLER_FILE}.app/Contents/MacOS/${QT_INSTALLER_FILE} --script qt-installer-${QT_VER}-noninteractive.qs
- hdiutil detach /Volumes/${QT_INSTALLER_FILE}
- rm -rf ${QT_INSTALLER_FILE}.dmg
- curl -L -O http://download.qt.io/development_releases/prebuilt/libclang/${LIBCLANG_FILE}
- 7z x ${LIBCLANG_FILE}
- export CLANG_INSTALL_DIR=$(pwd)/libclang
- rm -rf ${LIBCLANG_FILE}

install:
- git clone --recursive --branch 5.9 https://codereview.qt-project.org/pyside/pyside-setup        
- cd pyside-setup
#- git checkout 43451e3bc17467593df64cb73ce8c0bf9e60045f

before_deploy:
- cd ..
- ls -l pyside-setup/dist

deploy:
  skip_cleanup: true
  on: qt59-highsierra
  provider: bintray
  file: "bintray.json"
  user: alby128
  key:
    secure: "IHR96zDrlsxIVJF3SHZoQ5N8omEbneZgh1NN+qAkZshkadvXdt16rBXPzsifmTgiw9EeOjLpzCZvdnjDraYO+Pj/P5MSE3Zu2rVJ6FDFD9VjWcYKXqWFkRa21sm2oo0Xe+1SKnFqY8ACXKA1vFY448lBd0QnJhtbTJXHQLSJeoYm+8fDaQD8iPCanNac60nUsxGoRNVmSG/xl7DrENIdJ+enkvVleqh4ur6h+Urds8gXGncdj+aYQqmtVpbiKDS9tBBRKdnspi5JRBckd609FqB+AQA+l7vjnCBA3+XeHNLW/XE2l4g8D3msIrDpGNymLjHviL5wpm/p2MfaeoOxeJgeVl+tr/vA3gZm/TpYuo18jqFToUfPGm5Ox/SP4uT2drk7j8muHHwoFRflgIvqC96ormS3xCBBikUb87X9v7hTK722YWo7L1uH6ZVrTNhg4k4XS6x1+tg418lKkV034nIcDoXo/WUazRbwfPGhOtfdOVGXzbtAw1sR9ug0PwXWp1cxWI3Nlswo6kz3r9Qy2AHR2Wd75BAly7AFxRiubEWo+y0uDKC/JEHi7K2oaBsB7+5IvUw9zaisImrhjNDD2/ZDGrdCLZfzwHrv5DfX62fej8CHXdblcQ1BfIRUDYr6fNfLMvtJYiOs6KFgYn5fBjI563siVa/BRKPCfnFELTg="