language: objective-c
osx_image: xcode7.3

branches:
  only:
  - qt511-off-sources

env:
  global:
    - QT_VER=5.11.0
    - PYSIDE2_SOURCES_FILE=pyside-setup-everywhere-src-5.11.0.tar.xz
    - CI_QMAKE=/usr/local/opt/qt/bin/qmake
    - CLANG_INSTALL_DIR=/usr/local/opt/llvm

script:
- python setup.py install --ignore-git --no-examples --macos-use-libc++ --qmake=${CI_QMAKE} --cmake=/usr/local/bin/cmake --jobs=3

before_install:
- which python
- which pip
- brew install libxslt
- pip install --upgrade pip setuptools wheel
- brew install tree
- brew install llvm
- brew update
- brew install qt

install:
#- curl -O http://syncplay.s3.amazonaws.com/QSocketNotifier.patch
#- curl -O http://syncplay.s3.amazonaws.com/syncplayID.patch
#- git clone --recursive --branch v5.11.0 https://codereview.qt-project.org/pyside/pyside-setup
- curl -L -O http://download.qt.io/official_releases/QtForPython/pyside2/PySide2-5.11.0-src/pyside-setup-everywhere-src-5.11.0.tar.xz
- cd pyside-setup-everywhere-src-5.11.0
#- git rm sources/pyside2/tests/QtCore/qsocketnotifier_test.py
#- git apply ../QSocketNotifier.patch
#- git apply ../syncplayID.patch

before_deploy:
- python -c "from PySide2.QtCore import __version__; print __version__"
- ls -l
- ls -l dist

deploy:
  skip_cleanup: true
  on: qt511-off-sources
  provider: bintray
  file: "bintray.json"
  user: alby128
  key:
    secure: "IHR96zDrlsxIVJF3SHZoQ5N8omEbneZgh1NN+qAkZshkadvXdt16rBXPzsifmTgiw9EeOjLpzCZvdnjDraYO+Pj/P5MSE3Zu2rVJ6FDFD9VjWcYKXqWFkRa21sm2oo0Xe+1SKnFqY8ACXKA1vFY448lBd0QnJhtbTJXHQLSJeoYm+8fDaQD8iPCanNac60nUsxGoRNVmSG/xl7DrENIdJ+enkvVleqh4ur6h+Urds8gXGncdj+aYQqmtVpbiKDS9tBBRKdnspi5JRBckd609FqB+AQA+l7vjnCBA3+XeHNLW/XE2l4g8D3msIrDpGNymLjHviL5wpm/p2MfaeoOxeJgeVl+tr/vA3gZm/TpYuo18jqFToUfPGm5Ox/SP4uT2drk7j8muHHwoFRflgIvqC96ormS3xCBBikUb87X9v7hTK722YWo7L1uH6ZVrTNhg4k4XS6x1+tg418lKkV034nIcDoXo/WUazRbwfPGhOtfdOVGXzbtAw1sR9ug0PwXWp1cxWI3Nlswo6kz3r9Qy2AHR2Wd75BAly7AFxRiubEWo+y0uDKC/JEHi7K2oaBsB7+5IvUw9zaisImrhjNDD2/ZDGrdCLZfzwHrv5DfX62fej8CHXdblcQ1BfIRUDYr6fNfLMvtJYiOs6KFgYn5fBjI563siVa/BRKPCfnFELTg="