language: objective-c
osx_image: xcode7.3

branches:
  only:
  - qt59-py3

env:
  global:
    - QT_VER=5.9.5
    - CI_QMAKE=/usr/local/opt/qt/bin/qmake
    - LIBCLANG_FILE=libclang-release_50-mac-clazy.7z

script:
- python3 setup.py bdist_wheel --ignore-git --no-examples --osx-use-libc++ --qmake=${CI_QMAKE} --cmake=/usr/local/bin/cmake --jobs=3

before_install:
- brew update
- brew upgrade python
- which python3
- python3 --version
- which pip3
- pip3 --version
- brew install libxslt
- pip3 install --upgrade pip setuptools wheel
- brew install tree p7zip
- curl -O http://syncplay.s3.amazonaws.com/qt595.rb
- mv qt595.rb qt.rb
- brew install ./qt.rb
- curl -L -O http://download.qt.io/development_releases/prebuilt/libclang/${LIBCLANG_FILE}
- 7z x ${LIBCLANG_FILE}
- export CLANG_INSTALL_DIR=$(pwd)/libclang
- rm -rf ${LIBCLANG_FILE}

install:
- git clone --recursive --branch 5.9 https://codereview.qt-project.org/pyside/pyside-setup        
- cd pyside-setup

before_deploy:
- cd ..
- ls -l pyside-setup/dist

deploy:
  skip_cleanup: true
  on: qt59-py3
  provider: bintray
  file: "bintray.json"
  user: alby128
  key:
    secure: "IHR96zDrlsxIVJF3SHZoQ5N8omEbneZgh1NN+qAkZshkadvXdt16rBXPzsifmTgiw9EeOjLpzCZvdnjDraYO+Pj/P5MSE3Zu2rVJ6FDFD9VjWcYKXqWFkRa21sm2oo0Xe+1SKnFqY8ACXKA1vFY448lBd0QnJhtbTJXHQLSJeoYm+8fDaQD8iPCanNac60nUsxGoRNVmSG/xl7DrENIdJ+enkvVleqh4ur6h+Urds8gXGncdj+aYQqmtVpbiKDS9tBBRKdnspi5JRBckd609FqB+AQA+l7vjnCBA3+XeHNLW/XE2l4g8D3msIrDpGNymLjHviL5wpm/p2MfaeoOxeJgeVl+tr/vA3gZm/TpYuo18jqFToUfPGm5Ox/SP4uT2drk7j8muHHwoFRflgIvqC96ormS3xCBBikUb87X9v7hTK722YWo7L1uH6ZVrTNhg4k4XS6x1+tg418lKkV034nIcDoXo/WUazRbwfPGhOtfdOVGXzbtAw1sR9ug0PwXWp1cxWI3Nlswo6kz3r9Qy2AHR2Wd75BAly7AFxRiubEWo+y0uDKC/JEHi7K2oaBsB7+5IvUw9zaisImrhjNDD2/ZDGrdCLZfzwHrv5DfX62fej8CHXdblcQ1BfIRUDYr6fNfLMvtJYiOs6KFgYn5fBjI563siVa/BRKPCfnFELTg="