language: objective-c
osx_image: xcode7.3

branches:
  only:
  - qt511-py3

env:
  global:
    - QT_VER=5.11.1
    - CI_QMAKE=/usr/local/opt/qt/bin/qmake
    - CLANG_INSTALL_DIR=/usr/local/opt/llvm

script:
- python3 setup.py bdist_wheel --ignore-git --skip-docs --no-examples --macos-use-libc++ --qmake=${CI_QMAKE} --cmake=/usr/local/bin/cmake --jobs=3 --skip-modules=3DAnimation --skip-modules=3DCore --skip-modules=3DExtras --skip-modules=3DInput --skip-modules=3DLogic --skip-modules=3DRender --skip-modules=AxContainer --skip-modules=Charts --skip-modules=Concurrent --skip-modules=DataVisualization --skip-modules=Help --skip-modules=Location --skip-modules=Multimedia --skip-modules=MultimediaWidgets --skip-modules=OpenGL --skip-modules=Positioning --skip-modules=PrintSupport --skip-modules=Qml --skip-modules=Quick --skip-modules=QuickWidgets --skip-modules=Scxml --skip-modules=Sensors --skip-modules=Sql --skip-modules=Svg --skip-modules=Test --skip-modules=TextToSpeech --skip-modules=UiTools --skip-modules=WebChannel --skip-modules=WebSockets --skip-modules=WinExtras --skip-modules=Xml --skip-modules=XmlPatterns

before_install:
- brew uninstall python
- brew update
- curl -O https://raw.githubusercontent.com/Homebrew/homebrew-core/f2a764ef944b1080be64bd88dca9a1d80130c558/Formula/python.rb
- brew install ./python.rb
- which python3
- python3 --version
- which pip3
- pip3 --version
- brew install libxslt
- pip3 install --upgrade pip setuptools wheel
- brew install tree
- brew install llvm
- brew install qt

install:
- git clone --recursive --branch v5.11.1 https://codereview.qt-project.org/pyside/pyside-setup
- cd pyside-setup

before_deploy:
- cd ..
- ls -l pyside-setup/dist

deploy:
  skip_cleanup: true
  on: qt511-py3
  provider: bintray
  file: "bintray.json"
  user: alby128
  key:
    secure: "IHR96zDrlsxIVJF3SHZoQ5N8omEbneZgh1NN+qAkZshkadvXdt16rBXPzsifmTgiw9EeOjLpzCZvdnjDraYO+Pj/P5MSE3Zu2rVJ6FDFD9VjWcYKXqWFkRa21sm2oo0Xe+1SKnFqY8ACXKA1vFY448lBd0QnJhtbTJXHQLSJeoYm+8fDaQD8iPCanNac60nUsxGoRNVmSG/xl7DrENIdJ+enkvVleqh4ur6h+Urds8gXGncdj+aYQqmtVpbiKDS9tBBRKdnspi5JRBckd609FqB+AQA+l7vjnCBA3+XeHNLW/XE2l4g8D3msIrDpGNymLjHviL5wpm/p2MfaeoOxeJgeVl+tr/vA3gZm/TpYuo18jqFToUfPGm5Ox/SP4uT2drk7j8muHHwoFRflgIvqC96ormS3xCBBikUb87X9v7hTK722YWo7L1uH6ZVrTNhg4k4XS6x1+tg418lKkV034nIcDoXo/WUazRbwfPGhOtfdOVGXzbtAw1sR9ug0PwXWp1cxWI3Nlswo6kz3r9Qy2AHR2Wd75BAly7AFxRiubEWo+y0uDKC/JEHi7K2oaBsB7+5IvUw9zaisImrhjNDD2/ZDGrdCLZfzwHrv5DfX62fej8CHXdblcQ1BfIRUDYr6fNfLMvtJYiOs6KFgYn5fBjI563siVa/BRKPCfnFELTg="