language: objective-c
osx_image: xcode7.3

branches:
  only:
  - master

script:
- python setup.py bdist_wheel --ignore-git --no-examples --osx-use-libc++ --qmake=/usr/local/Cellar/qt5/5.6.1-1/bin/qmake --cmake=/usr/local/bin/cmake --openssl=/usr/local/Cellar/openssl/1.0.2h_1/bin --jobs=3

before_install:
- which python
- which pip
- curl -O https://raw.githubusercontent.com/Homebrew/homebrew-core/fdfc724dd532345f5c6cdf47dc43e99654e6a5fd/Formula/qt5.rb
- brew install ./qt5.rb
- brew install libxslt
- pip install --upgrade pip setuptools wheel

install:
- git clone --recursive --branch 5.6 https://codereview.qt-project.org/pyside/pyside-setup        
- cd pyside-setup

before_deploy:
- cd ..
- ls -l pyside-setup/dist

deploy:
  skip_cleanup: true
  on: master
  provider: bintray
  file: "bintray.json"
  user: alby128
  key:
    secure: "IHR96zDrlsxIVJF3SHZoQ5N8omEbneZgh1NN+qAkZshkadvXdt16rBXPzsifmTgiw9EeOjLpzCZvdnjDraYO+Pj/P5MSE3Zu2rVJ6FDFD9VjWcYKXqWFkRa21sm2oo0Xe+1SKnFqY8ACXKA1vFY448lBd0QnJhtbTJXHQLSJeoYm+8fDaQD8iPCanNac60nUsxGoRNVmSG/xl7DrENIdJ+enkvVleqh4ur6h+Urds8gXGncdj+aYQqmtVpbiKDS9tBBRKdnspi5JRBckd609FqB+AQA+l7vjnCBA3+XeHNLW/XE2l4g8D3msIrDpGNymLjHviL5wpm/p2MfaeoOxeJgeVl+tr/vA3gZm/TpYuo18jqFToUfPGm5Ox/SP4uT2drk7j8muHHwoFRflgIvqC96ormS3xCBBikUb87X9v7hTK722YWo7L1uH6ZVrTNhg4k4XS6x1+tg418lKkV034nIcDoXo/WUazRbwfPGhOtfdOVGXzbtAw1sR9ug0PwXWp1cxWI3Nlswo6kz3r9Qy2AHR2Wd75BAly7AFxRiubEWo+y0uDKC/JEHi7K2oaBsB7+5IvUw9zaisImrhjNDD2/ZDGrdCLZfzwHrv5DfX62fej8CHXdblcQ1BfIRUDYr6fNfLMvtJYiOs6KFgYn5fBjI563siVa/BRKPCfnFELTg="